-- identity-service/schema.sql
-- Postgres schema
-- - UUIDs generated by application (Hibernate)
-- - BIGINT catalogs generated by DB
-- - TIMESTAMPTZ everywhere
-- - DB defaults for timestamps (safe for seeds / raw SQL)
-- - No triggers

-- =========================
-- core tables
-- =========================

CREATE TABLE tenants (
    id         UUID PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    status     VARCHAR(30)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id           UUID PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    status       VARCHAR(30)  NOT NULL
        CHECK (status IN ('active','inactive','banned', 'suspended', 'archived')),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- =========================
-- tenant ↔ user (membership)
-- =========================

CREATE TABLE tenant_memberships (
    tenant_id  UUID NOT NULL,
    user_id    UUID NOT NULL,
    status     VARCHAR(30) NOT NULL
        CHECK (status IN ('active','invited','disabled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, user_id),

    CONSTRAINT fk_tm_tenant
        FOREIGN KEY (tenant_id)
            REFERENCES tenants(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_tm_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
);

CREATE INDEX idx_tm_user_id
    ON tenant_memberships(user_id);

-- =========================
-- roles (per-tenant)
-- =========================

CREATE TABLE roles (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id  UUID NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_roles_tenant
       FOREIGN KEY (tenant_id)
           REFERENCES tenants(id)
           ON DELETE CASCADE,

    CONSTRAINT uq_roles_tenant_name
       UNIQUE (tenant_id, name),

    -- required for composite FK from user_roles
    CONSTRAINT uq_roles_tenant_id_id
       UNIQUE (tenant_id, id)
);

CREATE INDEX idx_roles_tenant_id
    ON roles(tenant_id);

-- =========================
-- permissions (global catalog)
-- =========================

CREATE TABLE permissions (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    key        VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =========================
-- role ↔ permission
-- =========================

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_rp_role
      FOREIGN KEY (role_id)
          REFERENCES roles(id)
          ON DELETE CASCADE,

    CONSTRAINT fk_rp_permission
      FOREIGN KEY (permission_id)
          REFERENCES permissions(id)
          ON DELETE CASCADE
);

CREATE INDEX idx_rp_permission_id
    ON role_permissions(permission_id);

-- =========================
-- user ↔ role (scoped by tenant)
-- =========================

CREATE TABLE user_roles (
    tenant_id  UUID NOT NULL,
    user_id    UUID NOT NULL,
    role_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, user_id, role_id),

    -- user must belong to tenant
    CONSTRAINT fk_ur_membership
        FOREIGN KEY (tenant_id, user_id)
            REFERENCES tenant_memberships(tenant_id, user_id)
            ON DELETE CASCADE,

    -- role must belong to same tenant
    CONSTRAINT fk_ur_role_in_tenant
        FOREIGN KEY (tenant_id, role_id)
            REFERENCES roles(tenant_id, id)
            ON DELETE CASCADE
);

CREATE INDEX idx_ur_user_id
    ON user_roles(user_id);

CREATE INDEX idx_ur_role_id
    ON user_roles(role_id);
